exam_sys_proj/blueprints/auth.py
from flask import Blueprint, render_template, jsonify, redirect, url_for, session, flash
from exam_sys_proj.src.extensions import mail, dbPool
from flask_mail import Message
from flask import request
from .forms import RegisterForm, LoginForm
import bcrypt, random, string
from exam_sys_proj.dao.RegistrationCodeDAO import RegistrationCodeDAO, RegistrationCode
from exam_sys_proj.dao.UsersDAO import UsersDAO, Users
from datetime import datetime

# /auth
bp = Blueprint("auth", __name__, url_prefix="/auth")
users_operator = UsersDAO(dbPool)


@bp.route("/login", methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template("login.html")
    else:
        form = LoginForm(request.form)
        if form.validate():
            email = form.email.data
            password = form.password.data
            user: Users = users_operator.query(email, 'email')
            # user = Users.query.filter_by(email=email).first()
            if not user:
                # print("邮箱未注册！")
                flash(f"邮箱未注册！", 'danger')
                return redirect(url_for("auth.login"))
            if bcrypt.checkpw(password.encode("utf-8"), user.passWord):
                # cookie：
                # cookie中不适合存储太多的数据，只适合存储少量的数据
                # cookie一般用来存放登录授权的东西
                # flask中的session，是经过加密后存储在cookie中的
                session['user_id'] = user.userID
                if user.roleID == 1:
                    return redirect("/student/detail")
                if user.roleID == 2:
                    return redirect("/teacher/detail")
                if user.roleID == 3:
                    return redirect("/admin/detail")
            else:
                flash(f"密码错误！", 'danger')
                return redirect(url_for("auth.login"))
        else:
            for field, errors in form.errors.items():
                for error in errors:
                    # flash(f"Error in {getattr(form, field).label.text}: {error}", 'danger')
                    flash(f"{error}", 'danger')
            return redirect(url_for("auth.login"))


# GET：从服务器上获取数据
# POST：将客户端的数据提交给服务器
@bp.route("/register", methods=['GET', 'POST'])
def register():
    if request.method == 'GET':
        return render_template("register.html")
    else:
        # 验证用户提交的邮箱和验证码是否对应且正确
        # 表单验证：src-wtf: wtforms
        form = RegisterForm(request.form)
        if form.validate():
            email = form.email.data
            username = form.username.data
            password = form.password.data
            name = form.name.data
            user = Users(userName=username, passWord=password, name=name, roleID=1, email=email)
            users_operator.insert(user)
            # user = Users(email=email, username=username, password=generate_password_hash(password))
            # db.session.add(user)
            # db.session.commit()
            return redirect(url_for("auth.login"))
        else:
            for field, errors in form.errors.items():
                for error in errors:
                    # flash(f"Error in {getattr(form, field).label.text}: {error}", 'danger')
                    flash(f"{error}", 'danger')
            return redirect(url_for("auth.register"))
            # return render_template('register.html', form=form)


@bp.route("/logout")
def logout():
    session.clear()
    return redirect("/auth/login")


# bp.route：如果没有指定methods参数，默认就是GET请求
@bp.route("/captcha/email")
def get_email_captcha():
    register = RegistrationCodeDAO(dbPool)

    # /captcha/email/<email>
    # /captcha/email?email=xxx@qq.com
    email = request.args.get("email")
    # 4/6：随机数组、字母、数组和字母的组合
    # src = (string.digits+string.ascii_uppercase)*6
    # captcha = random.sample(src, 6)
    # captcha = "".join(captcha)
    # I/O：Input/Output
    registerOrm = RegistrationCode()
    message = Message(subject="好得不能再好了！测试系统验证码", recipients=[email],
                      body=f"恭喜您受邀参与“好得不能再好了测试系统”的内测，您的验证码是:{registerOrm.verificationCode}")
    mail.send(message)
    # memcached/redis
    # 用数据库表的方式存储
    register.SetVerificationCode(registerOrm, email)
    # email_captcha = RegistrationCode(email=email,verificationCode=captcha,expirationDate=datetime.datetime.now()+datetime.timedelta(minutes=5))
    # db.session.add(email_captcha)
    # db.session.commit()
    # RESTful API
    # {code: 200/400/500, message: "", data: {}}
    return jsonify({"code": 200, "message": "", "data": None})


@bp.route("/captcha/reset")
def get_reset_captcha():
    email = request.args.get("email")
    reset = RegistrationCodeDAO(dbPool)
    user: Users = users_operator.query(email, 'email')
    if not user:
        flash(f"邮箱未注册！", 'danger')
        return redirect(url_for("auth.forget"))
    registrationOrm = RegistrationCode()
    message = Message(subject="重置密码请求", recipients=[email],
                      body=f"您正在申请重置密码。您的验证码是:{registrationOrm.verificationCode}，如果您没有发起该请求，请忽略此邮件。")
    mail.send(message)
    reset.SetVerificationCode(registrationOrm, email)
    return jsonify({"code": 200, "message": "", "data": None})


@bp.route("/forget", methods=["GET", "POST"])
def forget():
    if request.method == "GET":
        return render_template("forget.html")
    else:
        form = request.form
        email = form.get("email")
        user: Users = users_operator.query(email, 'email')
        captcha = form.get("captcha").upper()
        varificater = RegistrationCodeDAO(dbPool)
        entity: RegistrationCode = varificater.query(email)
        if captcha != entity.verificationCode or entity.expirationDate < datetime.now():
            flash(f"验证码错误！", 'danger')
            return redirect(url_for("auth.forget"))
        if not user:
            # print("邮箱未注册！")
            flash(f"邮箱未注册！", 'danger')
            return redirect(url_for("auth.forget"))
        else:
            ran_password = ''.join(random.sample(string.ascii_letters + string.digits, 9))
            newpassword = Users(passWord=ran_password)
            users_operator.update(newpassword, user.userID)
            message = Message(subject="密码重置", recipients=[email],
                              body=f"您的密码已被重置为:{ran_password}。")
            mail.send(message)
            return redirect(url_for("auth.login"))


@bp.route("/mail/test")
def mail_test():
    message = Message(subject="邮箱测试", recipients=["2063331724@qq.com"], body="这是一条测试邮件")
    mail.send(message)
    return "邮件发送成功！"

exam_sys_proj/blueprints/student.py
from flask import Blueprint, render_template, jsonify, redirect, url_for, session, flash
from exam_sys_proj.src.extensions import mail, dbPool
from flask_mail import Message
from flask import request
from .forms import RegisterForm, LoginForm
import os, bcrypt, json, markdown
from markupsafe import Markup
from exam_sys_proj.dao.RegistrationCodeDAO import RegistrationCodeDAO, RegistrationCode
from exam_sys_proj.dao.UsersDAO import UsersDAO, Users
from exam_sys_proj.util.teacherUtils import TeacherUtils
from exam_sys_proj.dao.BroadcastShowDAO import BroadcastShowDAO
from ..dao.HepAndKpMediaterDAO import HepAndKpMediaterDAO
from ..dao.HomeworkOrExamPoolDAO import HomeworkOrExamPoolDAO
from ..dao.KnowledgePointsDAO import KnowledgePointsDAO
from ..dao.StudentCourseDAO import StudentCourseDAO
from ..dao.StudentHandInDAO import StudentHandInDAO
from ..dao.TeacherCourseDAO import TeacherCourseDAO
from ..orm.StudentHandIn import StudentHandIn
from ..util.StudentHandinUtils import StudentHandinUtils

# from ..dao.studentCourseDAO import studentCourseDAO

bp = Blueprint("student", __name__, url_prefix="/student")


class MyEncoder(json.JSONEncoder):

    def default(self, obj):
        """
        判断是否为bytes类型的数据是的话转换成str
        :param obj:
        :return:
        """
        if isinstance(obj, bytes):
            return str(obj, encoding='utf-8')
        return json.JSONEncoder.default(self, obj)


# http://127.0.0.1:5000
@bp.route("/detail")
def detail():
    broadcast_getter = BroadcastShowDAO(dbPool)
    broadcasts = broadcast_getter.get_user_All_Broadcast(session.get("user_id"))
    if broadcasts != 'noResult':
        for broadcast in broadcasts:
            broadcast.content = json.loads(broadcast.content)
            broadcast.content['message'] = Markup(
                markdown.markdown(broadcast.content['message'], extensions=['extra', 'codehilite', 'nl2br']))
    return render_template("student_detail.html", broadcasts=broadcasts)


@bp.route("/change_password", methods=["POST"])
def change_password():
    data = request.get_json()
    user_id = session.get("user_id")
    users_operator = UsersDAO(dbPool)
    user: Users = users_operator.query(user_id)
    if len(data['new_password']) < 9 or len(data['new_password']) > 20:
        return '密码长度需在9到20位之间！'
    elif bcrypt.checkpw(data['old_password'].encode("utf-8"), user.passWord):
        newpassword = Users(passWord=data['new_password'])
        users_operator.update(newpassword, user.userID)
        return '修改成功！'
    else:
        return '密码错误！'


@bp.route("/paper_create/<subject>", methods=["GET", "POST"])
def paper_create(subject):
    question_types = ['选择题', '判断题', '填空题', '主观题']
    knowledge_point_getter = KnowledgePointsDAO(dbPool)
    knowledge_points = knowledge_point_getter.query(subject, 'subject', True)
    if request.method == 'GET':
        return render_template("student_paper_create.html", question_types=question_types,
                               knowledge_points=knowledge_points)
    else:
        data = request.get_json()
        # print(data)
        paper = {}
        paper['title'] = data['title']
        paper['subject'] = data['subject']
        paper['type'] = data['type']
        paper['overall_difficulty_easy'] = data['overall_difficulty_easy']
        paper['overall_difficulty_normal'] = data['overall_difficulty_normal']
        paper['overall_difficulty_hard'] = data['overall_difficulty_hard']
        paper['get_answer'] = True
        if 'shuffle' in data:
            paper['shuffle'] = False
        else:
            paper['shuffle'] = True
        for question_type in question_types:
            paper[question_type] = {}
            if question_type != "主观题":
                paper[question_type]["score_per_question"] = data[question_type + "_score_per_question"]
            else:
                paper[question_type]["score_per_question"] = '0'
            paper[question_type]["difficulty_min"] = data[question_type + "_difficulty_min"]
            paper[question_type]["difficulty_max"] = data[question_type + "_difficulty_max"]
            paper[question_type]["amount_per_knowledge_point"] = {}
            for knowledge_point in knowledge_points:
                paper[question_type]["amount_per_knowledge_point"][knowledge_point.kpName] = data[
                    question_type + "_" + knowledge_point.kpName]
    result = TeacherUtils.random_paper(paper, dbPool)
    print(paper)
    if result['status_code'] == 404:
        return result['message']
    else:
        TeacherUtils.insertOneQuestion(dbPool, result['content'][1])
        inserter = StudentHandinUtils()
        inserter.insert_self_exam(dbPool, result['content'], session.get("user_id"))
        return result['content'][2]


@bp.route('/select_subject', methods=['POST', 'GET'])
def select_subject():
    if request.method == 'POST':
        subject = request.form['subject']
        # 将学科参数传递到新页面
        return {'redirect_url': f'/student/paper_create/{subject}'}
    else:
        subject_getter = TeacherCourseDAO(dbPool)
        subjects = subject_getter.getallsubject()
        if subjects:
            return render_template('student_select_subject.html', subjects=subjects)
        else:
            return "没有学科！"


@bp.route('/exam_list')
def exam_list():
    return render_template('student_exam.html')


@bp.route('/get_papers')
def get_papers():
    student_id = session.get("user_id")
    # papers: list[StudentHandIn] = student_hand_in_dao.query(student_id, 'userID', True)
    papers = StudentHandinUtils.get_user_test(dbPool, student_id)
    # print(papers)
    # paper_details = []
    # for paper in papers:
    #     paper_detail = {
    #         'paperID': paper.studentHandInID,
    #         'title': paper.content,
    #         'subject': paper,
    #         'score': paper.score
    #         # 'completed': paper.completed
    #     }
    #     paper_details.append(paper_detail)
    return json.dumps({
        'code': 0,
        'message': "成功！",
        'data': json.loads(papers)
    }, cls=MyEncoder)
    # return jsonify({'code': 0, 'data': papers})


# @bp.route('/view_paper', methods=['POST'])
# def view_paper():
#     data = request.get_json()
#     studentHandInID = data.get('studentHandInID')
#     return jsonify({'redirect_url': 'student.view_paper/'+studentHandInID})

@bp.route('/view_paper/{paper_id}', methods=['GET'])
def view_paper_detail(paper_id):
    teacherUtils = TeacherUtils()
    teacherUtils.getPaperForShow(paper_id, dbPool)


@bp.route('/start_exam/<paper_id>')
def start_exam(paper_id):
    teacherUtils = TeacherUtils()
    paper = teacherUtils.getPaperForShow(int(paper_id), dbPool)
    paper = json.dumps(paper, ensure_ascii=False)
    print(paper)
    return render_template('exam_answer.html', paper=paper, paper_id=paper_id)


@bp.route('/submit_answers', methods=['POST'])
def submit_exam():
    answers = request.get_json()
    print(answers)
    answers = answers['answers']
    # 处理答案，保存到数据库或其他逻辑
    # 示例：将答案打印到控制台
    paper_id = int(answers.pop())
    data = []
    for i in answers:
        temp = []
        if type(i) == int:
            i = str(i)
        temp.append(i)
        data.append(temp)
    print(f"HandIn ID: {paper_id}, Answers: {data}")
    studentHandInDAO = StudentHandInDAO(dbPool)
    data = json.dumps(data)
    entity = StudentHandIn(studentHandInID=paper_id, content=data)
    studentHandInDAO.update(entity, paper_id)
    StudentHandinUtils.auto_correct(dbPool, paper_id)
    return jsonify({'message': '答案提交成功！'})

exam_sys_proj/templates/admin_detail.html
{% extends "admin_base.html" %}

{% block body %}

    <div class="layui-row layui-col-space15">
        {% if broadcasts!='noResult' %}
            {% for broadcast in broadcasts %}
                <div class="layui-col-md6">
                    <div class="layui-card">
                        <div class="layui-card-header" {% if 'color' in broadcast.content %}
                             style="background-color: {{ broadcast.content['color'] }}" {% endif %}>
                            <h2>{{ broadcast.content['title'] }}</h2></div>
                        <div class="layui-card-body">
                            {{ broadcast.content['message']|safe }}
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% endif %}
        <div class="layui-col-md6">
            <div class="layui-card">
                <div class="layui-card-header" style="background-color: #f39c12;">更改密码</div>
                <div class="layui-card-body">
                    <form class="layui-form">
                        <div class="layui-form-item">
                            <div class="layui-input-wrap">
                                <div class="layui-input-prefix">
                                    <i class="layui-icon layui-icon-password"></i>
                                </div>
                                <input type="password" name="old_password" value="" lay-verify="required"
                                       placeholder="旧密码"
                                       autocomplete="off" class="layui-input" id="old_password" lay-affix="eye">
                            </div>
                        </div>
                        {% with messages = get_flashed_messages(with_categories=true) %}
                            <ul class="flashes">
                                {% for category, message in messages %}
                                    {% if message=="密码错误！" %}
                                        <li class="{{ category }}">{{ message }}</li>
                                    {% endif %}
                                {% endfor %}
                            </ul>
                        {% endwith %}
                        <div class="layui-form-item">
                            <div class="layui-input-wrap">
                                <div class="layui-input-prefix">
                                    <i class="layui-icon layui-icon-password"></i>
                                </div>
                                <input type="password" name="new_password" value="" lay-verify="required"
                                       placeholder="新密码"
                                       autocomplete="off" class="layui-input" id="new_password" lay-affix="eye">
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <div class="layui-input-wrap">
                                <div class="layui-input-prefix">
                                    <i class="layui-icon layui-icon-password"></i>
                                </div>
                                <input type="password" name="confirmPassword" value=""
                                       lay-verify="required|confirmPassword"
                                       placeholder="确认新密码" autocomplete="off" class="layui-input" lay-affix="eye">
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <button class="layui-btn layui-btn-fluid" lay-submit lay-filter="change">修改密码</button>
                        </div>
                        {% with messages = get_flashed_messages(with_categories=true) %}
                            <ul class="flashes">
                                {% for category, message in messages %}
                                    {% if message=="密码错误！" %}
                                        <li class="{{ category }}">{{ message }}</li>
                                    {% endif %}
                                {% endfor %}
                            </ul>
                        {% endwith %}
                    </form>
                </div>
            </div>
        </div>

    </div>
    <script>
        layui.use(function () {
            var $ = layui.$;
            var form = layui.form;
            var layer = layui.layer;

            // 自定义验证规则
            form.verify({
                // 确认密码
                confirmPassword: function (value, item) {
                    var passwordValue = $('#new_password').val();
                    if (value !== passwordValue) {
                        return '两次密码输入不一致';
                    }
                }
            });

            // 提交事件
            form.on('submit(change)', function (data) {
                var field = data.field; // 获取表单字段值
                var xhr = new XMLHttpRequest();
                xhr.open('POST', '/teacher/change_password', true);
                xhr.setRequestHeader('Content-Type', 'application/json');
                xhr.send(JSON.stringify(field));
                xhr.onreadystatechange = function () {
                    //若响应完成且请求成功
                    if (xhr.readyState === 4 && xhr.status === 200) {
                        layer.alert(xhr.responseText);
                    }
                };

                {#layer.alert(xhr.responseText());#}
                return false; // 阻止默认 form 跳转
            });
        });
    </script>
{% endblock %}

exam_sys_proj/templates/edit_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>编辑信息</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='layui/css/layui.css') }}">
    <script type="text/javascript" src="{{ url_for('static', filename='layui/layui.js') }}" charset="utf-8"></script>
    <link id="layui_theme_css" rel="stylesheet" href="{{ url_for('static', filename='css/layui-theme-dark.css') }}">
</head>
<body>
<div class="layui-fluid">
    <div class="layui-row layui-col-space15">
        <div class="layui-col-md12">
            <div class="layui-card">
                {#                <div class="layui-card-header">编辑用户</div>#}
                <div class="layui-card-body">
                    <form class="layui-form" action="/admin/users/update" method="post">
                        <input type="hidden" name="userID" value="{{ user.userID }}">
                        <div class="layui-form-item">
                            <label class="layui-form-label">用户名</label>
                            <div class="layui-input-block">
                                <input type="text" name="userName" value="{{ user.userName }}" required
                                       lay-verify="required" placeholder="请输入用户名" class="layui-input">
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">姓名</label>
                            <div class="layui-input-block">
                                <input type="text" name="name" value="{{ user.name }}" required lay-verify="required"
                                       placeholder="请输入姓名" class="layui-input">
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">邮箱</label>
                            <div class="layui-input-block">
                                <input type="email" name="email" value="{{ user.email }}" required
                                       lay-verify="required|email" placeholder="请输入邮箱" class="layui-input">
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">角色ID</label>
                            <div class="layui-input-block">
                                <input type="text" name="roleID" value="{{ user.roleID }}" required
                                       lay-verify="required" placeholder="请输入角色ID" class="layui-input">
                            </div>
                        </div>
                        {#                        <div class="layui-form-item">#}
                        {#                            <div class="layui-input-block">#}
                        {#                                <button class="layui-btn" lay-submit lay-filter="formDemo">立即提交</button>#}
                        {#                                <button type="reset" class="layui-btn layui-btn-primary">重置</button>#}
                        {#                            </div>#}
                        {#                        </div>#}
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

exam_sys_proj/templates/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>出错了</title>
</head>
<body>
出错了
</body>
</html>

exam_sys_proj/templates/student_base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>测试系统-学生端</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {#    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/bootstrap.4.6.min.css') }}">#}
    <link rel="stylesheet" href="{{ url_for('static', filename='layui/css/layui.css') }}">
    {#    <link rel="stylesheet" href="{{ url_for('static', filename='css/student.css') }}">#}
    <script type="text/javascript" src="{{ url_for('static', filename='jquery/jquery.js') }}" charset="utf-8"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='layui/layui.js') }}" charset="utf-8"></script>
</head>
<body style="background-color: #e8e8e8;">
<div class="layui-layout layui-layout-admin layui-bg-blue">
    <div class="layui-header layui-bg-blue">
        <div class="layui-logo layui-hide-xs layui-bg-blue">测试系统</div>
        <!-- 头部区域（可配合layui 已有的水平导航） -->
        <ul class="layui-nav layui-layout-right">
            {#            <li class="layui-nav-item layui-hide layui-show-sm-inline-block">#}
            {% if user %}
                <li class="layui-nav-item">
                    {{ user.userName }}
                </li>
                <li class="layui-nav-item">
                    <a class="nav-link" href="{{ url_for('auth.logout') }}">退出登录</a>
                </li>
            {% else %}
                <li class="layui-nav-item">
                    <a class="nav-link" href="{{ url_for('auth.login') }}">登录</a>
                </li>
                <li class="layui-nav-item">
                    <a class="nav-link" href="{{ url_for('auth.register') }}">注册</a>
                </li>
            {% endif %}
            {#            </li>#}
            {#            <li class="layui-nav-item" lay-header-event="menuRight" lay-unselect>#}
            {#                <a href="javascript:;">#}
            {#                    <i class="layui-icon layui-icon-more-vertical"></i>#}
            {#                </a>#}
            {#            </li>#}
        </ul>
    </div>
    <div class="layui-side layui-bg-blue">
        <div class="layui-side-scroll layui-bg-blue">
            <!-- 左侧导航区域（可配合layui已有的垂直导航） -->
            <ul class="layui-nav layui-nav-tree layui-bg-blue" lay-filter="test">
                <li class="layui-nav-item"><a href="{{ url_for('student.detail') }}">个人主页</a></li>
                {#                <li class="layui-nav-item"><a href="{{ url_for('student.class_manage') }}">我的班级</a></li>#}
                <li class="layui-nav-item"><a href="{{ url_for('student.exam_list') }}">测试</a></li>
                <li class="layui-nav-item"><a href="{{ url_for('student.select_subject') }}">自测</a></li>
            </ul>
        </div>
    </div>
    <div class="layui-body">
        <div class="layui-bg-gray" style="padding: 15px;">
            {#<div class="layui-bg-gray" style="padding: 16px;">#}

            {% block body %}{% endblock %}
            {#        <div class="layui-footer">#}
            {#            <!-- 底部固定区域 -->#}
            {#            底部固定区域#}
            {#        </div>#}
            {#    </div>#}
        </div>
    </div>
</div>

{#    <script src="//cdn.staticfile.org/layui/2.9.10/layui.js"></script>#}

<script>
    //JS
    layui.use(['element', 'layer', 'util'], function () {
        var element = layui.element;
        var layer = layui.layer;
        var util = layui.util;
        var $ = layui.$;

        //头部事件
        util.event('lay-header-event', {
            menuLeft: function (othis) { // 左侧菜单事件
                layer.msg('展开左侧菜单的操作', {icon: 0});
            },
            menuRight: function () {  // 右侧菜单事件
                layer.open({
                    type: 1,
                    title: '更多',
                    content: '<div style="padding: 15px;">处理右侧面板的操作</div>',
                    area: ['260px', '100%'],
                    offset: 'rt', // 右上角
                    anim: 'slideLeft', // 从右侧抽屉滑出
                    shadeClose: true,
                    scrollbar: false
                });
            }
        });
    });
    var a = document.getElementsByTagName('a');
    var url = document.URL;

    for (var i = 0; i <= a.length; i++) {
        //console.log(i);
        try {
            if (document.getElementsByTagName("a")[i].href === url) {
                document.getElementsByTagName("a")[i].classList.add("layui-this");
                document.getElementsByTagName('a')[i].parentElement.parentElement.parentElement.classList.add("layui-nav-itemed");
                //console.log(document.getElementsByTagName('a')[i].parentElement.parentElement.parentElement);
            }
        } catch (e) {
            {#pass;#}
        }
    }

</script>
</body>
</html>

{#<!DOCTYPE html>#}
{#<html>#}
{#<head>#}
{#    <meta charset="utf-8">#}
{#    <title>测试系统</title>#}
{#    <meta name="renderer" content="webkit">#}
{#    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">#}
{#    <meta name="viewport" content="width=device-width, initial-scale=1">#}
{#    <link href="//cdn.staticfile.org/layui/2.9.10/css/layui.css" rel="stylesheet">#}
{#</head>#}
{#<body>#}
{#<ul class="layui-nav layui-nav-tree layui-nav-side">#}
{#    <li class="layui-nav-item layui-hide layui-show-sm-inline-block">#}
{#        {% if user %}#}
{#            <li class="nav-item">#}
{#                <span class="nav-link">{{ user.username }}</span>#}
{#            </li>#}
{#            <li class="nav-item">#}
{#                <a class="nav-link" href="{{ url_for('auth.logout') }}">退出登录</a>#}
{#            </li>#}
{#        {% else %}#}
{#            <li class="nav-item">#}
{#                <a class="nav-link" href="{{ url_for('auth.login') }}">登录</a>#}
{#            </li>#}
{#            <li class="nav-item">#}
{#                <a class="nav-link" href="{{ url_for('auth.register') }}">注册</a>#}
{#            </li>#}
{#        {% endif %}#}
{#    <dl class="layui-nav-child">#}
{#        <dd><a href="javascript:;">Your Profile</a></dd>#}
{#        <dd><a href="javascript:;">Settings</a></dd>#}
{#        <dd><a href="javascript:;">Sign out</a></dd>#}
{#    </dl>#}
{#    </li>#}
{#    <li class="layui-nav-item"><a href="javascript:;">我的信息</a></li>#}
{#    <li class="layui-nav-item"><a href="javascript:;">班级管理</a></li>#}
{#    <li class="layui-nav-item"><a href="javascript:;">试卷管理</a></li>#}
{#    <li class="layui-nav-item"><a href="javascript:;">试题管理</a></li>#}
{#    <li class="layui-nav-item"><a href="javascript:;">试题创建</a></li>#}
{#    <li class="layui-nav-item"><a href="javascript:;">试题导入</a></li>#}
{#    <li class="layui-nav-item"><a href="javascript:;">试题导出</a></li>#}
{#</ul>#}
{#<script src="//cdn.staticfile.org/layui/2.9.10/layui.js"></script>#}
{#<script>#}
{#    layui.use(function () {#}
{#        var element = layui.element;#}
{#        element.render('nav');#}
{#    });#}
{#</script>#}
{#</body>#}
{#</html>#}